// <auto-generated />
using System;
using Biographic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biographic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250405121736_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biographic.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Biographic.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Австралия"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Австрия"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Англия"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Аржентина"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Белгия"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Бразилия"
                        },
                        new
                        {
                            Id = 7,
                            Name = "България"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Германия"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Гърция"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Дания"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Египет"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Испания"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Италия"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Индия"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Иран"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Ирландия"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Исландия"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Канада"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Китай"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Мексико"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Нидерландия"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Норвегия"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Полша"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Португалия"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Русия"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Румъния"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Саудитска Арабия"
                        },
                        new
                        {
                            Id = 28,
                            Name = "САЩ"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Сърбия"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Турция"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Украйна"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Унгария"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Финландия"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Франция"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Чехия"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Чили"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Швейцария"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Швеция"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Южна Африка"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Япония"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Ямайка"
                        });
                });

            modelBuilder.Entity("Biographic.Models.PeopleCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserCatalogsId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserCatalogsId");

                    b.HasIndex("UserId");

                    b.ToTable("PeopleCatalogs");
                });

            modelBuilder.Entity("Biographic.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDead")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ProfessionId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Теоретичен физик, известен с разработването на теорията на относителността. Носител на Нобелова награда за физика през 1921 година.",
                            CountryId = 37,
                            EndDate = new DateTime(1955, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Алберт Айнщайн",
                            ProfessionId = 33,
                            ProfileImage = "person1.jpg",
                            StartDate = new DateTime(1879, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Италиански ренесансов художник, изобретател и учен. Автор на Мона Лиза и Тайната вечеря.",
                            CountryId = 13,
                            EndDate = new DateTime(1519, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Леонардо да Винчи",
                            ProfessionId = 37,
                            ProfileImage = "person2.jpg",
                            StartDate = new DateTime(1452, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Пионер в радиологията, носител на две Нобелови награди - за физика и химия.",
                            CountryId = 24,
                            EndDate = new DateTime(1934, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Мария Кюри",
                            ProfessionId = 36,
                            ProfileImage = "person3.jpg",
                            StartDate = new DateTime(1867, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Ямайски състезател по лека атлетика, световен рекордьор в бягането на 100 и 200 метра.",
                            CountryId = 41,
                            IsDead = false,
                            Name = "Усейн Болт",
                            ProfessionId = 29,
                            ProfileImage = "person4.jpg",
                            StartDate = new DateTime(1986, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Руски писател, автор на 'Престъпление и наказание' и 'Братя Карамазови'.",
                            CountryId = 25,
                            EndDate = new DateTime(1881, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Фьодор Достоевски",
                            ProfessionId = 20,
                            ProfileImage = "person5.jpg",
                            StartDate = new DateTime(1821, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Южноафрикански политик и борец срещу апартейда, президент на ЮАР (1994-1999).",
                            CountryId = 39,
                            EndDate = new DateTime(2013, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Нелсън Мандела",
                            ProfessionId = 21,
                            ProfileImage = "person6.jpg",
                            StartDate = new DateTime(1918, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Biography = "Австрийски композитор, един от най-влиятелните в класическата музика.",
                            CountryId = 2,
                            EndDate = new DateTime(1791, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Волфганг Амадеус Моцарт",
                            ProfessionId = 16,
                            ProfileImage = "person7.jpg",
                            StartDate = new DateTime(1756, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Biography = "Италиански скулптор, художник и архитект от епохата на Ренесанса.",
                            CountryId = 13,
                            EndDate = new DateTime(1564, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Микеланджело Буонароти",
                            ProfessionId = 28,
                            ProfileImage = "person8.jpg",
                            StartDate = new DateTime(1475, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Biography = "Индийски политик и духовен лидер, водач на движението за независимост на Индия.",
                            CountryId = 14,
                            EndDate = new DateTime(1948, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Махатма Ганди",
                            ProfessionId = 21,
                            ProfileImage = "person9.jpg",
                            StartDate = new DateTime(1869, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Biography = "Последна царица на Древен Египет, известна с интелигентността и политическите си умения.",
                            CountryId = 11,
                            EndDate = new DateTime(69, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Клеопатра",
                            ProfessionId = 18,
                            ProfileImage = "person10.jpg",
                            StartDate = new DateTime(30, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Biography = "Испански художник, създател на кубизма, един от най-влиятелните художници на 20 век.",
                            CountryId = 12,
                            EndDate = new DateTime(1973, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Пабло Пикасо",
                            ProfessionId = 37,
                            ProfileImage = "person11.jpg",
                            StartDate = new DateTime(1881, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Biography = "Основател на Монголската империя, един от най-успешните военачалници в историята.",
                            CountryId = 28,
                            EndDate = new DateTime(1227, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Чингиз Хан",
                            ProfessionId = 7,
                            ProfileImage = "person12.jpg",
                            StartDate = new DateTime(1162, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Biography = "Владетелка на Хабсбургската монархия, една от най-влиятелните жени в европейската история.",
                            CountryId = 2,
                            EndDate = new DateTime(1780, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Мария Тереза",
                            ProfessionId = 18,
                            ProfileImage = "person13.jpg",
                            StartDate = new DateTime(1717, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Biography = "Съосновател на Apple Inc., пионер в компютърната индустрия.",
                            CountryId = 28,
                            EndDate = new DateTime(2011, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Стив Джобс",
                            ProfessionId = 25,
                            ProfileImage = "person14.jpg",
                            StartDate = new DateTime(1955, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Biography = "Немски астроном, известен с формулирането на законите за движение на планетите.",
                            CountryId = 8,
                            EndDate = new DateTime(1630, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Йоханес Кеплер",
                            ProfessionId = 5,
                            ProfileImage = "person15.jpg",
                            StartDate = new DateTime(1571, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Biography = "Френска модна дизайнерка, основателка на модната къща Chanel.",
                            CountryId = 34,
                            EndDate = new DateTime(1971, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Коко Шанел",
                            ProfessionId = 10,
                            ProfileImage = "person16.jpg",
                            StartDate = new DateTime(1883, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Biography = "Немски композитор, един от най-великите в историята на класическата музика.",
                            CountryId = 5,
                            EndDate = new DateTime(1827, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Лудвиг ван Бетховен",
                            ProfessionId = 16,
                            ProfileImage = "person17.jpg",
                            StartDate = new DateTime(1770, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Biography = "Италиански астроном и физик, наричан 'бащата на модерната наука'.",
                            CountryId = 13,
                            EndDate = new DateTime(1642, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Галилео Галилей",
                            ProfessionId = 31,
                            ProfileImage = "person18.jpg",
                            StartDate = new DateTime(1564, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Biography = "Еврейско момиче, автор на известния дневник от времето на Холокоста.",
                            CountryId = 21,
                            EndDate = new DateTime(1945, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Ан Франк",
                            ProfessionId = 20,
                            ProfileImage = "person19.jpg",
                            StartDate = new DateTime(1929, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Biography = "Английски натуралист, автор на теорията за еволюцията чрез естествен отбор.",
                            CountryId = 7,
                            EndDate = new DateTime(1882, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDead = true,
                            Name = "Чарлз Дарвин",
                            ProfessionId = 6,
                            ProfileImage = "person20.jpg",
                            StartDate = new DateTime(1809, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Biographic.Models.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Авиатор"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Актьор"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Архитект"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Астронавт"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Астроном"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Биолог"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Военачалник"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Готвач"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Диригент"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Дизайнер"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Дипломат"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Драматург"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Журналист"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Изобретател"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Инженер"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Композитор"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Математик"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Монарх"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Музикант"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Писател"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Политик"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Поет"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Преводач"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Преподавател"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Програмист"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Психолог"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Режисьор"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Скулптор"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Спортист"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Теоретик"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Учен"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Фармацевт"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Физик"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Философ"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Фотограф"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Химик"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Художник"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Шахматист"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Експлоратор"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Икономист"
                        });
                });

            modelBuilder.Entity("Biographic.Models.UserCatalogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsersCatalogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PeopleCatalogPerson", b =>
                {
                    b.Property<int>("PeopleCatalogsId")
                        .HasColumnType("int");

                    b.Property<int>("PeopleId")
                        .HasColumnType("int");

                    b.HasKey("PeopleCatalogsId", "PeopleId");

                    b.HasIndex("PeopleId");

                    b.ToTable("PeopleCatalogPerson");
                });

            modelBuilder.Entity("Biographic.Models.PeopleCatalog", b =>
                {
                    b.HasOne("Biographic.Models.UserCatalogs", null)
                        .WithMany("PeopleCatalog")
                        .HasForeignKey("UserCatalogsId");

                    b.HasOne("Biographic.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Biographic.Models.Person", b =>
                {
                    b.HasOne("Biographic.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biographic.Models.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("Biographic.Models.UserCatalogs", b =>
                {
                    b.HasOne("Biographic.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Biographic.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Biographic.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biographic.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Biographic.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeopleCatalogPerson", b =>
                {
                    b.HasOne("Biographic.Models.PeopleCatalog", null)
                        .WithMany()
                        .HasForeignKey("PeopleCatalogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biographic.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Biographic.Models.UserCatalogs", b =>
                {
                    b.Navigation("PeopleCatalog");
                });
#pragma warning restore 612, 618
        }
    }
}
